
#Pour la production
ia:
  api:
    url:${IA_API_URL}
#spring
spring:
  application:
    name: hysacam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate :
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: ${MAIL_URL}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          smtp:
            starttls:
              enable: true
